PrefectHQ/prefect-design

- demo/sections/components/ButtonGroup.vue
- src/components/ButtonGroup/PButtonGroup.vue
Closes https://github.com/PrefectHQ/prefect-design/issues/330
> Enhancement: Allow for string values for p-button-group

- demo/components/ComponentPage.vue
- demo/sections/components/Heading.vue
- demo/sections/components/index.ts
- src/components/HashLink/PHashLink.vue
- src/components/Heading/PHeading.vue
- src/components/Heading/index.ts
- src/components/MarkdownRenderer/parser.ts
- src/components/index.ts
> Feature: PHeading component

- demo/sections/components/CodeHighlight.vue
- src/components/CodeHighlight/worker.ts
- src/types/codeHighlight.ts
This PR adds support for YAML syntax highlighting in the `PCodeHighlight` component
> Enhancement: YAML highlighting

- src/components/CodeHighlight/worker.ts
> Chore: Remove errant console statement

- demo/sections/components/Timeline.vue
- src/components/Timeline/PTimeline.vue
- src/components/Timeline/PTimelineItem.vue
- src/types/timeline.ts
Putting into code an idea I poorly described in the PR this branch is being made to.
> Enhancement PTimeline layout refactor

- package-lock.json
- package.json
Fixes type errors when running the dev task related to vue-tsc and typescript 5.0.0
> Chore: Fix dev errors

- src/components/MarkdownRenderer/PMarkdownRenderer.vue
This PR slightly modifies the margins for paragraph and heading elements by using last and first child selectors
> Enhancement: Position-aware margins on paragraph and heading elements

- package-lock.json
- package.json
- src/components/ButtonGroup/PButtonGroup.vue
- src/components/Combobox/PCombobox.vue
- src/components/Stepper/PStepper.vue
- src/components/Table/PTableBody.vue
- src/components/TagsInput/PTagsInput.vue
- src/components/VirtualScroller/PVirtualScroller.vue
- src/components/Wizard/PWizard.vue
Updates to latest vue and fixes broken withDefaults imports.
> Chore: Update vue@3.3.4

- src/compositions/useDrawer.ts
- src/compositions/useModal.ts
Also fixes an incorrect type reference for `useModal`
> Bugfix: `useDrawer` and `useModal` should accept non-refs

- demo/sections/components/Modals.vue
- src/components/Modal/PModal.vue
Closes https://github.com/PrefectHQ/prefect-design/issues/408
> Enhancement: Scroll modal body if modal is taller than viewport

- demo/sections/components/ButtonGroup.vue
- src/components/ButtonGroup/PButtonGroup.vue
- src/types/buttonGroupOption.ts
Updates the types for options and modelValue to include booleans.
> Enhancement: Allow booleans for PButtonGroup

- src/components/Accordion/PAccordion.vue
Adds a selected boolean to the slot scope of the slots
> Enhancement: Add `selected` to slot scope of accordion slots

- demo/sections/components/BaseInput.vue
- public/tailwindPlugin.js
- src/components/Accordion/PAccordion.vue
- src/components/BaseInput/PBaseInput.vue
- src/styles/index.css
Updated styles utilizing tokens for the base input and accordion components
> Base input and accordion

- demo/components/AppNavigationBar.vue
- demo/components/CodeBlock.vue
- demo/components/ComponentPage.vue
- demo/sections/WelcomePage.vue
- demo/sections/components/BreadCrumbs.vue
- demo/sections/components/ButtonGroup.vue
- demo/sections/components/Buttons.vue
- demo/sections/components/Drawer.vue
- demo/sections/components/EmptyState.vue
- demo/sections/components/ListTruncate.vue
- demo/sections/components/Modals.vue
- demo/sections/components/Stepper.vue
- demo/sections/components/Tab.vue
- demo/sections/components/Table.vue
- demo/sections/components/Timeline.vue
- demo/sections/components/Tooltip.vue
- demo/sections/components/Window.vue
- demo/sections/layouts/LayoutResizable.vue
- src/components/Button/PButton.vue
- src/components/ButtonGroup/PButtonGroup.vue
- src/components/ListTruncate/PListTruncate.vue
- src/components/Message/PMessage.vue
- src/components/NativeDateInput/PNativeDateInput.vue
- src/components/NavigationBar/PNavigationBar.vue
- src/components/Pager/PPager.vue
- src/styles/index.css
- Updates the `p-button-group` component.
- Updates button usage throughout the repo to use the updated props.
- A couple minor tweeks to demo stuff is sprinkled in here as well.
> propigate updated buttons throughout repo

- demo/sections/components/Select.vue
- public/tailwindPlugin.js
- src/components/CodeInput/PCodeInput.vue
- src/components/Combobox/PCombobox.vue
- src/components/NativeSelect/PNativeSelect.vue
- src/components/Select/PSelect.vue
- src/components/Select/PSelectButton.vue
- src/components/Select/PSelectOptions.vue
- src/components/SelectOption/PSelectOption.vue
- src/components/SelectOptionGroup/PSelectOptionGroup.vue
- src/components/TextInput/PTextInput.vue
- src/styles/index.css
styles for select inputs and menus. Only piece remaining is the tag styling in the input when `multiple`, will style the tags component separately though.
> style select and combobox

- src/components/GlobalNavItem/PGlobalNavItem.vue
- src/components/HashLink/PHashLink.vue
- src/components/IconText/PIconText.vue
- src/components/KeyValue/PKeyValue.vue
- src/components/Label/PLabel.vue
- src/components/Link/PLink.vue
- src/styles/index.css
Series of text component style updates as I work my way down the component list.
> style various text components

- src/components/Message/PMessage.vue
- src/styles/index.css
The final color values will probably be tweeked at a later time, but this implements the tokens at least.
> Style PMessage

- demo/sections/components/OverflowMenu.vue
- src/components/Modal/PModal.vue
- src/components/NativeDateInput/PNativeDateInput.vue
- src/components/NavigationBar/PNavigationBar.vue
- src/components/OverflowMenu/POverflowMenu.vue
- src/components/OverflowMenuItem/POverflowMenuItem.vue
A series of style updates:
- PModal
- OverflowMenu
- PNativeDateInput
> styles for modals, overflow menus, and some inputs

- demo/sections/components/Tags.vue
- public/tailwindPlugin.js
- src/components/Checkbox/PCheckbox.vue
- src/components/Icon/PIcon.vue
- src/components/Radio/PRadio.vue
- src/components/Tab/PTab.vue
- src/components/Tabs/PTabNavigation.vue
- src/components/Tag/PTag.vue
- src/components/Wizard/PWizardStepHeader.vue
- src/styles/index.css
Updated styles for radio inputs, tabs, tags, and wizard.
> Radio inputs, tabs, tags, wizard

- demo/sections/components/Tags.vue
- src/components/Tags/PTags.vue
Exposes the default slot for each tag displayed in the PTags component.
> Enhancement: Add a slot for customizing tags in the p-tags component

- demo/sections/components/ButtonGroup.vue
- package-lock.json
- package.json
- src/components/ButtonGroup/PButtonGroup.vue
- src/components/ContextSidebar/PContextSidebar.vue
- src/components/Message/PMessage.vue
- src/components/OverflowMenu/POverflowMenu.vue
- src/components/OverflowMenuItem/POverflowMenuItem.vue
- src/components/Tab/PTab.vue
- src/components/Window/PWindow.vue
- src/layouts/PLayoutTable/PLayoutTable.vue
- src/styles/index.css
- src/types/buttonGroupOption.ts
Apologies for the larger PR, I did try and break the commits up as I went though!
> Resolve v2 feedback

- src/styles/index.css
Before:
After:
Applied to radios as well
> fix checked color

- src/components/ErrorBoundary/index.ts
- src/components/index.ts
> Bugfix: Make sure error boundary is exported

- src/layouts/PLayoutTable/PLayoutTable.vue
Adds some gap by default and adds flex-wrap to prevent blowout.
> Enhancement: PLayoutTable flex fixes for header slots

- src/types/dateRange.ts
Enhances the types for DateRangeSelectValue to allow for type safe guarding of the `type` property.
> Enhance types to more easily allow for type guarding date range type

- src/types/dateRange.ts
Just a type guard that was missing
> Add type guard for date range around unit

- package-lock.json
- package.json
- vite.config.ts
vue-compositions was pinned which was preventing newer versions from being used in upstream projects
> Fix vue-compositions being pinned and also not a peer

- src/styles/index.css
> Design: Lower base font size 16 => 14

- src/styles/index.css
Reverts PrefectHQ/prefect-design#1117
> Revert "Design: Lower base font size 16 => 14"
