demo/sections/components/CodeHighlight.vue, demo/sections/components/CodeInput.vue, src/components/CodeHighlight/PCodeHighlight.vue
Effects both p-code-highlight and p-code-input. Adding `overflow-auto` to p-code-highlight fixes it for both. Closes https://github.com/PrefectHQ/prefect-ui-library/issues/604
Before
After
=> BugFix: Code component overflow

src/components/Combobox/PCombobox.vue
PCombobox wouldn't show the selected value if the value was null and there was an option with a null value. This was due to some falsey checks that needed to be strict.
=> BugFix: PCombobox null option support

src/components/Table/PTable.vue
I have use p-table to display a list and I would like to navigate to the specific item of the list on row click. 
the event that gets emitted
```ts
{ row: TableData, rowIndex: number }
```
example use case
```html
<p-table @row:click="({row, rowIndex}) => ...">
```
=> Feature: added new emit for p-table row click

demo/sections/components/OverflowMenu.vue, src/components/OverflowMenuItem/POverflowMenuItem.vue
uses same logic from p-button to allow developer to pass route directly to component instead of nesting inside router-link component. Might be worth trying to encapsulate the shared logic between p-button and p-overflow-menu-item if we keep finding that logic repeated in future components.
```html
<p-overflow-menu-item label="Google" to="https://www.google.com" />
<p-overflow-menu-item label="Icons" :to="{ name: 'icons' }" />
```
closes #679
=> Feature: p-overflow-menu-item to prop

demo/sections/components/Toggle.vue, src/components/Toggle/PToggle.vue
this PR actually fixes a few issues
1. the p-toggle itself was not focusable, so a toggle without buttons in prepend/append slot was not navigable by keyboard
2. even if it was focusable, space keypress would not toggle the value [as expected by APG](https://www.w3.org/WAI/ARIA/apg/patterns/switch/)
3. we were also missing "role" on the label. I don't believe we actually needed to add the aria-checked, since we're using a checkbox underneath, but I can't imagine it hurts to have redundancy here
4. if the toggle is pending, the loading icon was not properly centered
before:
https://user-images.githubusercontent.com/6098901/225179855-2bf8b44e-6e24-43a7-ae35-358a4d4ad082.mov
https://user-images.githubusercontent.com/6098901/225179872-94a98b9a-9e59-4770-8f36-9681eff4965e.mov
after: …
=> BugFix: keyboard interactions on p-toggle

demo/sections/components/Modals.vue, src/components/Modal/PModal.vue
added `auto-close` prop behavior (closes modal on mask click) similar to how p-pop-over auto-close prop works
also adds prop `prevent-focus`, which let's the developer prevent automatic focusing of first focusable element on modal opening.
https://user-images.githubusercontent.com/6098901/225753876-aad23e0f-4ab2-4989-b281-60832ac432b1.mov
=> Feature: p-modal auto-close

src/components/DateInput/PDateInput.vue, src/components/DatePicker/PTimePicker.vue, src/components/NativeDateInput/PNativeDateInput.vue, src/compositions/useTimeParts.ts
as you probably know, p-date-input has a prop for `show-time`, which lets the user set both the date and the time.
as you probably also know, p-date-input relies on p-native-date-input if `media.hover`, which ignores `show-time`.
https://user-images.githubusercontent.com/6098901/225978874-d86ec99e-c210-4983-9d46-730a59dc2f5b.mov
https://user-images.githubusercontent.com/6098901/225979201-e7e3df13-5830-4bff-a159-16889ef2311b.MP4
my solution to add support for `show-time` prop on p-native-date-input, which puts an icon in the input that toggles between entering the "date" portion and entering the "time" portion.
https://user-images.githubusercontent.com/6098901/225978965-fa77245d-e99f-4f80-9c98-00a370005d62.mov
https://user-images.githubusercontent.com/6098901/225978988-b708bdfd-2a9b-4a33-80 …
=> Feature: p-native-datepicker new show-time prop

src/components/Calendar/PCalendar.vue
Not sure when it happened, but I found this weird sizing bug on safari
https://user-images.githubusercontent.com/6098901/225976162-73e25deb-93bb-49ad-b988-38fdad05ea65.mov
I didn't see any recent change that explain it, but the solution I came up with is explicit row sizing for the grid on p-calendar.
A side-effect of that decision (could be pro, could be con) is that the size of each row is the same regardless of if the month has 4, 5 or 6 weeks.
https://user-images.githubusercontent.com/6098901/225976425-3e8e97e0-5e5a-42a4-ae0b-b7be3f50edc8.mov
Here's a before/after for chrome, you can see the size of content changes depending on # of weeks in viewing month
https://user-images.githubusercontent.com/6098901/225976491-246f973b-68fe-4dc2-9a69-a988cd3fba25.mov …
=> BugFix: sizing of p-calendar date rows

src/components/Combobox/PCombobox.vue
prop and events that expose previously internal `typedValue` (now called `searchValue`)
```html
<p-combobox v-model="value" :option="options" @update:searchValue="respondToSearch" />
```
developer could also theoretically tie the value to another value or pre-populate the search with `v-model:searchValue`
planning to use this to fetch options async as user types, think of like an address input that brings in results from google maps as you type your address
=> Feature: expose searchValue on p-combobox

src/components/Divider/PDivider.vue
Matching the colors from PCard
Before
After
=> BugFix: PDivider not very visible

src/components/Message/PMessage.vue
Issue: info message background not visible in light mode
Before Dark
After Dark
Before Light
After Light
=> BugFix: PMessage background and dismiss button colors improvements

demo/sections/components/Card.vue, src/components/Card/PCard.vue
Pretty straightforward enhancement to the `PCard` component that adds a boolean `flat` property that removes the component's border, background, and box-shadow but keeps the padding. It also transitions all of these except box shadow.
=> Enhancement: PCard flat prop + animation

src/components/ListItem/PListItem.vue, src/components/ListItemInput/PListItemInput.vue
now developers can have a @click event on <p-list-item-input /> that will not get triggered by selection change
this PR also fixes some incorrect BEM classes on `p-list-item` and `p-list-item-input`
=> Chore: List item and list item input BEM classes

src/components/Modal/PModal.vue
looks like original implementation mistook the 2nd argument as boolean for "should the class be there or not" when in reality the 2nd argument is a boolean for "force". 
https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/toggle
also ensure bg-scroll gets re-enabled if p-modal gets unmounted without resetting `showModal`
=> BugFix: make sure bg can scroll after modal is closed

src/components/Tabs/PTabs.vue
The class that was added to PTabSelect was causing a warning because that component uses fragments. Seems like it shouldn't be a fragment component but rather than refactor I'm removing the unused class that was causing the warning.
=> Chore: Fix extraneous non-props warning in PTabs

src/components/PopOver/PPopOver.vue
This makes it easier for a developer to implement logic around the content of a popover without creating new refs at implementation
=> Enhancement: Expose target and content refs for PPopOver

src/components/Timeline/PTimelineItem.vue
The date and content had no gap when stacked. Adds some margin to the date to be consistent with the `--p-timeline-item-gap` custom property
=> Enhancement: Add margin to timeline date when stacked

src/components/CodeInput/PCodeInput.vue
Contained overscroll is only really nice for small inputs; large inputs capture too much passive scrolling and lead to a poor UX if they don't pass the event up the chain.
=> Bugfix: Remove overscroll-contain on PCodeInput

src/components/Button/PButton.vue
On dark mode the border of the "inset" style is too dark and doesn't provide enough contrast. Making the border lighter for dark mode make it much more distinguishable. 
Before
After
=> Enhancement: Increase PButton inset style contrast in dark mode

src/components/Tabs/PTabs.vue
When rendering tabs the entire tab object is being used as the `key`. This means tabs are not reused if the tabs array is updated. Switching the key to be the tab label to enable vue to accurately track tabs.
=> BugFix: PTabs key bound to tab object

src/components/Tab/PTab.vue
The tabs on the Flow Run Page are falling off the viewport.
Currently:
This shrinks them down so they look like this:
https://user-images.githubusercontent.com/6776415/233161085-82acc9d8-522c-47a0-92f7-af616ae6e185.mov
=> reduce the size of pTab

demo/sections/components/CodeInput.vue, src/components/CodeInput/PCodeInput.vue
These changes enhance the functionality of `PCodeInput` by:
- introducing the ability to specify a minimum number of lines to display. 
- fixing a bug where the placeholder text was limited to a small area of the input 
- updating the line number calculation to take placeholder text into account
I removed several wrapper elements and streamlined some of the CSS. The input now uses a combination of resize observers and input handlers instead of relying on CSS for dynamic sizing. As a result, the textarea underlay and code view overlay will now fill an appropriate amount of space (previously they shrunk to fit their contents).
These changes (hopefully) provide a better user experience when interacting with the input with text that doesn't span the entire width in LTR mode as the cursor will …
=> Enhancement: `PCodeInput` placeholder and line numbers

src/components/Icon/PIcon.vue
#742 bumped our heroicons version to latest, which contains a bug in how modules are resolved within the package. This means that downstream consumers of our package are getting a commonjs bundle instead of an esm-compatible one. A fix has been merged to the upstream but I'm not sure of their release cadence so we can use this as a shim in the meantime.
=> Bugfix: Use esm path to import icons

src/components/VirtualScroller/PVirtualScroller.vue
Previously the slot scope type for `item` was hard coded to `any`. With generics we can make that inferred.
=> Enhancement: Use generics for p-virtual-scroller

src/components/Select/PSelectOptions.vue, src/components/VirtualScroller/PVirtualScroller.vue
Middle ground between the options in the following issue. Added a gradient overlay when you can scroll down. Not against adding the icon as well but IMO its a little confusing on if you can click on it or what. 
Closes https://github.com/PrefectHQ/prefect-design/issues/774
=> Enhancement: Add visual queue to p-selection options dropdown when there is overflow

src/components/Button/PButton.vue
This PR fixes an issue where inset buttons had hover styles that matched the background, which made them feel unresponsive. It also makes the flat button actually flat by removing the background and shadow
=> Bugfix: `PButton` flat and inset styles

src/components/NavigationBar/PNavigationBar.vue
This PR passes layout-dependent classes to the append slot (previously they weren't being applied)
=> Bugfix: `PNavigationBar` layout class wasn't applied

demo/sections/components/ListTruncate.vue, demo/sections/components/index.ts, src/components/ListTruncate/PListTruncate.vue, src/components/ListTruncate/index.ts, src/components/index.ts
This PR introduces a new utility component, `PTruncatedList`, that allows incrementally showing/hiding an item list. It wraps `PVirtualScroller` and so takes all properties of that component as well as the following:
- `shown` (optional, default `5`) - the number of items shown initially
- `increment` (optional, default `5`) - the number of items added when more items are requested
- `decrement` (optional, default `n - increment`) - the number of items to remove when fewer are requested
- `buttonLabel` (optional, defaults to `Show more`) - a shorthand way of modifying the default button
This component is designed to be used with a pretty simple list but I included a demo to show a more complex asynchronous example.
=> Feature: Truncated list component

src/components/Card/PCard.vue, src/components/Code/PCode.vue, src/components/CodeHighlight/PCodeHighlight.vue, src/components/EmptyState/PEmptyState.vue, src/components/Table/PTable.vue, src/components/Table/PTableBody.vue
Update card styles in preparation for the dashboard design initiative. Also aims to bring a few card variants in line, in the interest of consistency.
I have a list of styles to hit up in `prefect-ui-library` as well:
```
.workspace-dashboard-card
.organization-dashboard-card
.work-pools-list
.logs__divider
```
=> update card styles

src/components/Modal/PModal.vue
Old light mode:
New light mode:
Old dark mode:
New dark mode:
=> fix modal styles

src/components/ContextNavItem/PContextNavItem.vue
Fixes the color of active nav items to be static rather than changing with the theme. Dark mode looked fine, but light mode was pretty muddy, so both light and dark now use the same value as was previously used on just dark mode.
Old:
New:
=> fix active nav item color in light mode

src/components/MarkdownRenderer/parser.ts, src/types/markdownRenderer.ts
Escape tokens were falling through before and ending up as empty block elements.
This will fix an issue where any escaped slash after the first is invisible. 
Related: https://github.com/PrefectHQ/prefect/issues/9816
=> Bugfix: Add handling for escape tokens

demo/sections/components/Tab.vue, src/components/Tabs/PTabNavigation.vue, src/components/Tabs/PTabSelect.vue, src/components/Tabs/PTabs.vue
Adding generic heading and content slots allows using a single component for all the tab headings/content. Which is useful if your tab prop is a union type that can be passed to another component.
=> Enhancement: Add support for generic `heading` and `content` slots in PTabs

src/components/ListItemInput/PListItemInput.vue
Instead of animating the checkboxes and drawing a lot of undue attention to them, have them statically sit in the corner.
=> remove checkbox animation from PListItemInput

demo/sections/components/Code.vue, src/components/Code/PCode.vue
The current border radius on the `p-code` component leads to inline code snippets having overly-round corners, particularly when the snippet is short. 
Before:
After:
=> Enhancement: PCode inline border radii

src/components/PopOver/PPopOver.vue
This PR fixes an issue where popover groups were generating IDs that required a secure context (due to the usage of the crypto module). Instead, we issue a call to the `randomId` module that provides a shim if crypto isn't available.
=> Bugfix: Remove bare crypto call in PPopover

src/components/DateInput/PDateButton.vue, src/components/DateInput/PDateInput.vue
Specifically set out to solve the issue where the selected time was not shown unless you opened the input. Made some overall changes to how we format and display the text/date/time. Feedback welcome
No value before
No value after
No value and `showTime` before
No value and `showTime` after
Date selected before
Date selected after
Date and time selected before
Date and time selected after
=> Enhancement: Better date formatting of selected date and time in p-date-input

src/components/DateInput/PDateButton.vue, src/components/DateRangeInput/PDateRangeInput.vue
Fixes an issue where selecting the same start and end date would result in a date difference of 0 minutes. Should also fix issues where ranges of dates wouldn't include some data when using those dates directly for filters and queries. 
Closes https://github.com/PrefectHQ/prefect/issues/7917
This change forces the start date to always be 00:00:00 and the end date to be 59:59:59 by using date-fns startOfDate and endOfDay utilities.
Side quest: Also updated the formatting when displaying the dates to match PDateInput
=> BugFix: PDateRange use correct times

src/components/Textarea/PTextarea.vue
PTextarea can be resized where user cannot see the text.
Set min-height to e 2.5rem. This is calculated by lineHight of 1.5rem + padding-top of .5rem and padding-bottom of .5rem.
=> BugFix: PTextarea can be resized where user cannot see the text. 

src/components/Tooltip/PTooltip.vue
Long tooltip content makes wide and skinny tooltips
Added a max-width of max-w-xs to the tooltip
Screenshot of tooltip on desktop
Screenshot of tooltip on mobile
=> BugFix: Long tooltip content makes wide and skinny tooltips

demo/components/PositionSelect.vue, demo/sections/components/PopOver.vue, src/utilities/position.ts
This PR adds some new positions for aligning PPopOver. It also reduces the complexity of the popover select demo component to make adding new positions a little easier
=> Enhancement: More positions!

demo/sections/components/Checkbox.vue, src/components/Card/PCard.vue, src/components/Checkbox/PCheckbox.vue, src/components/CheckboxGroup/PCheckboxGroup.vue
Updated styles for cards and checkboxes
=> Cards and checkboxes

demo/sections/components/ContextSidebar.vue, demo/sections/components/index.ts, src/components/ContextAccordionItem/PContextAccordionItem.vue, src/components/ContextDivider/PContextDivider.vue, src/components/ContextNavItem/PContextNavItem.vue, src/components/ContextSidebar/PContextSidebar.vue, src/styles/index.css
Context sidebar components and the nav accordion component.
=> styles for context sidebar components

demo/sections/WelcomePage.vue, demo/sections/components/Buttons.vue, src/components/Button/PButton.vue, src/components/ButtonGroup/PButtonGroup.vue, src/components/Calendar/PCalendar.vue, src/components/Combobox/PCombobox.vue, src/components/ContextSidebar/PContextSidebar.vue, src/components/DateInput/PDateButton.vue, src/components/DateInput/PDateInput.vue, src/components/DatePicker/PDatePicker.vue, src/components/DatePicker/PMonthPicker.vue, src/components/DatePicker/ScrollingPicker.vue, src/components/DateRangeInput/PDateRangeInput.vue, src/components/IconButtonMenu/PIconButtonMenu.vue, src/components/Modal/PModal.vue, src/components/Stepper/PStepper.vue, src/components/Terminal/PTerminal.vue, src/components/Wizard/PWizard.vue, src/styles/index.css
Styles the DateInput, DatePicker, and DateRangeInput components. I also hit up some buttons I missed previously as my find-all was for `<p-button` but there were a number of `<PButton` instances out there.
=> style date pickers

demo/sections/components/Table.vue, src/components/ListItem/PListItem.vue, src/components/ListItemInput/PListItemInput.vue, src/components/MarkdownRenderer/PMarkdownRenderer.vue, src/components/Table/PTable.vue, src/components/Table/PTableBody.vue, src/components/Table/PTableData.vue, src/components/Table/PTableFoot.vue, src/components/Table/PTableHead.vue, src/components/Table/PTableHeader.vue, src/styles/index.css
As I updated styles for the markdown renderer, I notices tables got some special styles for a sticky header. I had previously removed the bg from tables with the intent to make them sit in cards and let the card handle bg-colors, but seeing this and auditing how we use tables a bit, I added the bg's back to the table on the header and body independently so they work with the sticky header.
=> style markdown renderer and tables

demo/sections/components/Dialog.vue, demo/sections/components/index.ts, src/components/Dialog/PDialog.vue, src/components/Dialog/index.ts, src/components/index.ts
Adds a new `PDialog` component which is a reactive wrapper around the [dialog](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog) element. It has a single default slot which binds a close method. This component does not add any opinionated styling and is designed to be styled at implementation. 
- open - `boolean` (required)
- autoClose - `boolean`
- modal - `boolean`
=> Feature: PDialog component

src/components/Dialog/PDialog.vue
Adds open and close events for developer convenience for any cleanup/init that needs to happen when the dialog is opened or closed
=> Enhancement: Add open and close events to p-dialog

src/components/ContextNavItem/PContextNavItem.vue
Makes the `to` prop optional. This follows how PButton works so that the nav item can either be a router link or a button.
=> Enhancement: Allow PContextNavItem to be a button by making `to` optional

src/compositions/useColorTheme.ts
Removes `prefers-color-scheme` defaults; library theming will now default to `dark` in all instances where a stored theme isn't available but will still respect toggling through either application or OS logic at runtime.
=> Chore: Only respect the stored theme, always default to dark

src/components/CodeInput/PCodeInput.vue, src/styles/index.css
This token wasn't named properly and was easily confused with other text color tokens.
=> fix naming of selection-highlight token

src/components/DatePicker/PDatePicker.vue, src/components/DatePicker/PMonthPicker.vue, src/components/DatePicker/ScrollingPicker.vue, src/components/DateRangeInput/PDateRangeInput.vue
Since updating the selected color, it's not functioning great in the date picker. If we find another instance where this selected state of buttons is an issue, I may refactor the approach here. For now I'm just considering these selected states as a "checked" sort of state.
After:
Before:
=> fix date input selectables

src/components/ContextAccordionItem/PContextAccordionItem.vue, src/components/ContextNavItem/PContextNavItem.vue, src/components/OverflowMenuItem/POverflowMenuItem.vue
This PR: 
- fixes an issue where context accordion items weren't highlighting properly when a child route was matched and the accordion was closed
- fixes an issue where context nav items were highlighted when matched inexactly (this doesn't preclude downstream consumers from passing `active-class` but probably better matches our intent here)
- adds an active class to overflow menu items
=> Bugfix: Nav item active class inconsistencies

src/components/Tooltip/PTooltip.vue
Adds the ability to disable a tooltip by adding the `disabled` prop. This will allow for tooltips to be conditional based on some implementation detail.
=> Enhancement: Add disabled prop to PTooltip

src/components/ListItem/PListItem.vue
There's not really a reason to flex the slot, downstream consumers should be responsible for that
=> Bugfix: Don't flex default slot

demo/sections/components/Select.vue, src/components/Select/PSelect.vue, src/types/utilities.ts
Currently if you try and pass a readonly array of options into PSelect it will error. Adding `MaybeReadonly` to this repository and using it for the `options` prop to make using this component easier.
=> BugFix: Allow PSelect options to be readonly

src/components/Combobox/PCombobox.vue
The `search` prop was already an optional v-model but there was no way to tell the combobox to not perform the filter. Adding a `manual` prop to skip all internal filtering and let the implementation dictate the filtering for the options. 
This allows filtering to be async (done via an api)
=> Enhancement: Add manual prop to PCombobox to skip internal filtering

src/components/Combobox/PCombobox.vue, src/components/Select/PSelect.vue, src/components/Select/PSelectOptions.vue
Since there's already an infinite scroll component in PSelectOptions, bubbling that up through the parent components means implementations can utilize that event.
=> Enhancement: Bubble up the bottom event from the virtual scroller in PSelect & PCombobox

src/components/DatePicker/PTimePicker.vue, src/components/DatePicker/ScrollingPicker.vue
Resolves https://github.com/PrefectHQ/prefect/issues/10693
Date pickers in safari were janky, apparently due to safari's old school IE like nature and how it handles flexbox styles. This hardens the styles so they perform better.
Before in Safari:
https://github.com/PrefectHQ/prefect-design/assets/6776415/a5128db5-99f0-4852-87f9-93280502f2d6
After in Safari:
https://github.com/PrefectHQ/prefect-design/assets/6776415/d1a15f4c-e44a-44b3-8a56-0422869acb87
=> harden date picker scroller styles

src/components/Select/PSelectOptions.vue
Fixes an issue with the new `bottom` event that is bubbled up where it would not be emitted if `options` was an empty array. This means at implementation you would have to load some results in order to then get the `bottom` event to fire. 
Reworked the empty state to be inside of the virtual scroller so that the bottom event is emitted even if there are no options to display. 
This means async options can wait to be loaded until a combobox is opened.
=> BugFix: PSelectOptions doesn't emit `bottom` event when results are empty

src/components/Select/PSelect.vue
`PSelect` was making an implicit assumption that the model value for the component would exist in the list of options and thereby render the `empty-message` slot if a value was set but not present. This is problematic in circumstances where options are fetched on-demand from an async source or when paginating the options list.
=> Bugfix: `PSelect` empty message

demo/sections/components/Stepper.vue, src/components/Stepper/PStepper.vue
p-stepper does not currently accept `disabled` prop. It sort of works by passing that prop through to the underlying p-number-input component but the buttons used in prepend and append are stick clickable and still appear to modify the value. 
this change makes `disabled` an expected prop, uses to disable stepper buttons and still passes through to underlying p-number-input
=> Fix stepper disabled

src/components/Tabs/PTabSelect.vue
this change could theoretically introduce a breaking change if any thing was using PTabSelect and expected `tab` to be string. Theoretically any slot that accounted for this would have a case for `tab` being `{ label: string }`, which will always be the case now and shouldn't cause any issues.
closes #988
=> update slot props on PTabSelect to be consistent with PTabNavigation

src/components/OverflowMenuItem/POverflowMenuItem.vue
The deployment menu in Prefect has this implicit extra spacing
| With `<template #after />` | **Before** | **After** |
| :----: | ---- | ---- |
| ✅ | <img width="311" alt="image" src="https://github.com/PrefectHQ/prefect-design/assets/22418768/48b816f6-898e-480d-b7ec-96fcff1cf534"> | <img width="289" alt="image" src="https://github.com/PrefectHQ/prefect-design/assets/22418768/ec327c8e-4829-40cf-9a25-ed404a30e01b"> |
| ❌ | <img width="302" alt="image" src="https://github.com/PrefectHQ/prefect-design/assets/22418768/5bbdd37e-9602-4a68-a840-40d4f270c46f"> | <img width="297" alt="image" src="https://github.com/PrefectHQ/prefect-design/assets/22418768/bdb5d0b2-03e1-4b42-b2ef-d0a10252ee2c"> |
=> Remove p-overflow-menu-item's after slot styling if no slot content is provided.

src/layouts/PLayoutWell/PLayoutWell.vue
Remove the bump in padding on large screens for PLayoutWell so that it matches PLayoutDefault and things line up nicely on the pages.
=> fix large screen padding in well layout

src/components/MarkdownRenderer/parser.ts, src/components/SanitizeHtml/PSanitizeHtml.vue
This PR updates the markdown renderer and sanitize html components to better improve their security posture.
`PSanitizeHtml` no longer allows `form` elements and explicitly forbids `script`, `style`, and `iframe` elements instead of relying on the default behavior of DOMPurify.
It also explicitly strips the following HTML attributes: 
- `action`
- `method`
- `onclick`
- `onmouseover`
- `onload`
- `data`
`PMarkdownRenderer`'s parser now also adds `rel="noopener"` to all markdown-created links (ones generated by `[link](https://some-link)`) as an added layer of protection against tab/window hijacking
=> Enhancement: Improved sanitization

src/components/SanitizeHtml/PSanitizeHtml.vue, src/components/Unwrap/PUnwrap.vue
This will provide downstream consumers a way to override the component defaults as necessary without needing to re-implement the component.
Note: I've also updated allowed types for both `PSanitizeHtml` and `PUnwrap` due to the change in overload coming from the config.
=> Enhancement: Allow passing sanitization config to `PSanitizeHtml` component

demo/sections/layouts/LayoutTable.vue, src/layouts/PLayoutTable/PLayoutTable.vue
Creates a dedicated space in the table header for sort options, so it can be separated with a divider from other filter options:
=> add sort placement in table layout header

src/components/Label/PLabel.vue
You cannot access the label's generated id without it being bound to the slot. Adding it to all the rest of the slots.
=> Enhancement: PLabel - Bind the id to all slots so its accessible

demo/sections/components/NativeTimeInput.vue, demo/sections/components/index.ts, src/components/NativeDateInput/PNativeDateInput.vue, src/components/NativeTimeInput/PNativeTimeInput.vue, src/components/NativeTimeInput/index.ts, src/components/index.ts
Updates the existing native date input component and adds a new native time input component.
Works exactly the same as before with the exception of removing the ability to also enter time. Which now has a dedicated input for. Also fixes an issue where if a date that already had time was v-model'd the time would be reset. This way the same date can be bound to both the date and the time inputs
Time
Almost identical to the native date input in functionality. Also preserves the date of the v-model when updating the time.
=> Native date and time input components

public/tailwindPlugin.js, src/styles/index.css
At the moment, our custom sentiment colors don't work with tailwind's [opacity modifiers](https://tailwindcss.com/docs/text-color#changing-the-opacity). So it's difficult to take our design token as-is and apply an alpha channel to it without having to break out of the design system and losing the ability to "just update the color in one place". This PR addresses this issue.
The current system defines colors using CSS variables which have hex color values. Hex doesn't support the alpha channel color modifier syntax (`{value} / {opacity}`) which Tailwind will use for its opacity modifiers so we need to switch over to either RGB or HSL. 
1. Swap from hex to RGB/HSL
2. Tailwind needs the "raw" values (or for RGB, color channels) to then use within an `rgb`/`hsl` function so we provide a …
=> Make sentiment colors work with tw opacity modifiers

src/layouts/PLayoutDefault/PLayoutDefault.vue
```html
<p-layout-default>
<p>some content</p>
</p-layout-default>
```
Produces an extra 16px of top spacing because it expects header content. This PR skips rendering the slot if there's no content provided so that there's no child element to produce the 16px grid gap.
Should maybe consider deprecating the header slot entirely as it doesn't provide a ton.
=> Remove vertical space when p-layout-default header slot unused.

package-lock.json, package.json
Noticed this npm warning while installing packages
```
WARN deprecated @types/tailwindcss@3.1.0: This is a stub types definition. tailwindcss provides its own type definitions, so you do not need this installed.
```
Confirmed by https://www.npmjs.com/package/@types/tailwindcss
So uninstalling the package.
=> Chore: Remove @types/tailwindcss

src/components/Textarea/PTextarea.vue
When a template ref is passed into a `<p-textarea>` component, it gets caught at `PBaseInput` so it's otherwise _difficult_ to get a reference to the underlying `<textarea>` element.
```vue
<template>
<p-textarea :v-model="..." ref="elRef" />
</template>
<script setup lang="ts">
...
const elRef = ref<InstanceType<typeof PTextarea>>()
onMounted(() => {
elRef.value.focus()  // nope. it's a component template ref
elRef.value.$el.focus()  // _nope_. elRef.$el is an HTMLDivElement 😱 b/c it falls through onto <PBaseInput>
elRef.value.$el.querySelector("textarea")?.focus()  // 🙈 well this works at least
})
```
This PR follows the same pattern/convention as `PTextInput` which just _exposes_ a property called `el` on the component's VM. In the above example, you can now do …
=> Expose PTextarea's `<textarea>` element.

src/components/NativeSelect/PNativeSelect.vue, src/components/Select/PSelect.vue, src/components/Select/PSelectOptions.vue, src/components/TypeAhead/PTypeAhead.vue, src/utilities/arrays.ts
Small refactor so that PSelectOptions can be used on its own without reproducing all of the logic for highlighting and selecting values.
=> Chore: Update PSelectOptions to handle its own selection logic

src/components/TypeAhead/PTypeAhead.vue
https://github.com/PrefectHQ/prefect-design/pull/1034 Accidentally removed the filtering of the type ahead component.
=> Bugfix: Fix filtering not working

src/components/DateInput/PDateInput.vue, src/components/DateInput/PInputPopOver.vue, src/components/DateRangeInput/PDateRangeInput.vue, src/components/DateRangePicker/PDateRangePicker.vue, src/components/DateRangePicker/index.ts, src/components/index.ts
Over reliance on slots was making it hard to reuse the date range input's picker for the new date range select. Separating out more of the functionality between the date input and the date range input will make it a lot simpler to work with these component. 
Note: These components should remain functionally and visually the same.
=> Chore: Separate the PDateInput and PDateRangeInput

src/compositions/useThemeTokens.ts
Fixes the issue where tokens would be empty strings when the page first loads.
=> Fix useThemeTokens returning empty tokens on first render

demo/sections/components/Divider.vue, src/components/Divider/PDivider.vue
=> Add a slot to p-divider for a centered item with space around.

demo/sections/components/DateRangeSelect.vue, demo/sections/components/index.ts, src/components/DateInput/PDateInput.vue, src/components/DatePicker/PDatePicker.vue, src/components/DateRangeInput/PDateRangeInput.vue, src/components/DateRangePicker/PDateRangePicker.vue, src/components/DateRangeSelect/PDateRangeSelect.vue, src/components/DateRangeSelect/PDateRangeSelectOptions.vue, src/components/DateRangeSelect/index.ts, src/components/DateRangeSelect/utilities.ts, src/components/DateTimeInputGroup/PDateTimeInputGroup.vue, src/components/NativeDateInput/PNativeDateInput.vue, src/components/SelectOption/PSelectOption.vue, src/components/index.ts
The date range select is a new component for selecting date ranges either of a fixed date/time or a relative time span like "Past 15 minutes". 
It has a single v-model that returns a value based on the user's selection. If a relative value is selected the number of seconds in the selected span is returned. If a fixed range is selected the start and end dates are returned. This value can be type guarded with the `modelValue.type` which is either `span` or `range`
Recommend checking out the [deploy preview ](https://deploy-preview-1048--prefect-design.netlify.app/components/date-range-select)and playing around this the component. 
Relative span
Fixed date range
=> Feature: PDateRangeSelect

src/components/Select/PSelect.vue
If a select or combobox is using the bottom event to async load options no options will appear if a native select is used. This can happen if the `media.hover` check is false. 
Emitting the `bottom` event when the native select is mounted ensures at least the first page of results is shown. 
Note: This is a stop gap to get options showing at all. To restore full functionality to mobile devices we'll need to rethink our mobile strategy for selects
=> BugFix: Emit the bottom event if the native select is mounted

src/components/Select/PSelect.vue
The `multiple` check got changed accidentally to look at the internal model rather than the prop and that caused empty arrays to not be considered as an empty value.
=> Fix PSelect empty message not showing up

src/components/DateRangePicker/PDateRangePicker.vue, src/components/DateRangeSelect/PDateRangeSelect.vue
Fixes the label overflowing the button if there is not enough room. Also allows the popover to be closed by pressing escape. Also updates the date range picker's styling to match the border radius to the buttons.
=> Enhancement: PDateRangeSelect overflow and escape to close

src/layouts/PLayoutDefault/PLayoutDefault.vue
This is all part of some effort to make the dashboard header more responsive. Prevents flex content from blowing out the container.
=> Fix: prevent default layout header blowouts

demo/sections/components/Tags.vue, demo/sections/components/TagsInput.vue, src/components/Select/PSelect.vue, src/components/TagWrapper/PTagWrapper.vue
The tags input required a fixed width to really take advantage of the `+n` overflow display. This made it so the input was unusually long on the dashboard or never read out the selected tags:
This PR makes it so that the tags list has an inline option and will allow the input to scale with the content.
https://github.com/PrefectHQ/prefect-design/assets/6776415/06893d8f-f0ff-409b-a833-5a556cad4c66
https://github.com/PrefectHQ/prefect-design/assets/6776415/0ce71b18-0e10-45cc-91fb-573326f8a387
=> Fix: tags input not taking advantage of available width

.vscode/settings.json, src/components/ListHeader/PListHeader.vue
=> Fix: Prevent long content from blowing out the list header

demo/sections/components/Tags.vue, src/components/Tag/PTag.vue, src/components/Tags/PTags.vue
=> Add sizes for tags

src/layouts/PLayoutDefault/PLayoutDefault.vue, src/layouts/PLayoutFull/PLayoutFull.vue, src/layouts/PLayoutWell/PLayoutWell.vue
Layouts had a height assignment of 100%, but these weren't neccesary. It made it so that if a layout had content above (e.g. the incidents banner) or below it, the height of the layout would be the height of it's inner+neighboring content, causing too much padding at the bottom of it's inner contents and causing the left navigation to scroll. CSS is weird and hard sometimes.
=> Fix: remove height 100% from layouts

src/components/DatePicker/PDatePicker.vue, src/components/DateRangePicker/PDateRangePicker.vue, src/components/DateRangeSelect/PDateRangeDurationInput.vue, src/components/DateRangeSelect/PDateRangeSelect.vue, src/components/DateRangeSelect/PDateRangeSelectAround.vue, src/components/DateRangeSelect/PDateRangeSelectOptions.vue, src/components/DateRangeSelect/PDateRangeSelectRange.vue, src/components/DateRangeSelect/PDateRangeSelectRelative.vue, src/components/DateRangeSelect/utilities.ts, src/types/dateRange.ts, src/utilities/dateRangeSelect.ts, src/utilities/index.ts
Adds a third "mode" to the date range select for "Around a time". Also moved the relative values into their own option called "Relative time". This gives us more room for other modes like "Today" to be front and center in the options.
=> Add support for "around" to the date range select

src/components/DateRangeSelect/PDateRangeSelect.vue, src/components/DateRangeSelect/PDateRangeSelectOptions.vue, src/components/DateRangeSelect/utilities.ts, src/types/dateRange.ts, src/utilities/dateRangeSelect.ts
Adds "Today" and as a "period" options to the DateRangeSelect component. Added "Today", "Past hour", 'Past day", and "Past week" as shortcut options visible when first opening the input.
=> Add "period" as a date range value type for things like "Today"

src/components/DateRangeSelect/PDateRangeSelectRelative.vue
Previously only the number value was considered when typing into the search. Now it will also filter the options based on any string value. So the search `20m` will filter the results to `Past 20 minutes` and `Next 20 minutes`. Also supports `20 min`, `minutes`, etc
Also adds visual indicators of shortcuts for filtering
=> Allow filtering by unit when using the DateRangeSelect's relative time dropdown

src/components/DateRangeSelect/PDateRangeSelect.vue
Matches the width of the options dropdowns to the width of the input same as inputs like PSelect and PCombobox.
=> Sync the option dropdowns with the width of the input

src/components/Stepper/PStepper.vue
This brings the `PStepper` component more in line with the HTML spec by no longer preventing the v-models from updating when a user has entered a value outside the range of described by the `min` and `max` attrs
=> Enhancement: `PStepper` should always emit user-entered values

src/components/Modal/PModal.vue, src/plugins/Modal/index.ts, src/plugins/index.ts
Currently modals get teleported to the body. Which is fine but its not predictable. So I'm introducing a plugin that creates a div on the body so that all modals get teleported to that div. 
This allows for some consistency and also means we can add css around the assumption that nothing but modals will be in that div. Will be building off this to fix some block creation UX where users can lose the work they were doing because of redirects.
=> Enhancement: Modal plugin for consistent teleporting of modals

src/components/DraggableList/PDraggableList.vue
Makes some tweaks to the keydown handler so that enter and delete are combined with shift. Otherwise if you use the slot and use something like a code input or a textarea adding a newline adds a new item. Also not being able to use the delete is bad. So adding shift to those. I think the arrow keys will also need some tweaking. But leaving those for now.
=> PDraggableList: Only prevent default if taking an action. Add shift to enter and delete

demo/sections/DesignTokens.vue, src/styles/index.css
Because the schema form UI can reach a third layer of card nesting relatively easily, we're adding a third level bg token that otherwise should be considered undesirable to use. 
Dark mode:
Light mode:
=> Enhancement: add lvl-3 bg color token

src/utilities/dateRangeSelect.ts
Because a span like "Past 1 day" uses a negative time interval, the `mapDateRangeSelectSpanValueToDateRange` needs to return the absolute interval for use in downstream next/previous calculations. When simply returning the same interval, a negative interval for Past 1 Day would be converted into a positive interval for calculating a previous time (on press of the "previous" button), which would make it progress forward a day.
Before:
https://github.com/PrefectHQ/prefect-design/assets/6776415/ef2d92d8-8997-4030-ade6-fed7ba513fca
After:
https://github.com/PrefectHQ/prefect-design/assets/6776415/0e115af0-f970-4471-95d8-1cb06d71b1f6
=> bugfix: date-range-select span to range transition

src/components/DateRangeSelect/utilities.ts
Instead of saying "Previous 1 hour" or "Next 1 day", selected date range spans should now say "Previous hour" or "Next day"
=> Enhancement: Improve language on selected date span label

src/components/TagWrapper/PTagWrapper.vue
=> Enhancement: Use a tooltip instead of a title tag for overflowing tags

src/components/Divider/PDivider.vue
Fixes small regression from https://github.com/PrefectHQ/prefect-design/pull/1037
|     | **Before** | **After** |
| ---- | ---- | ---- |
| Deployment details well | <img width="355" alt="image" src="https://github.com/PrefectHQ/prefect-design/assets/22418768/37512f9f-7dd7-4292-a823-09e52d7b2777"> | <img width="305" alt="image" src="https://github.com/PrefectHQ/prefect-design/assets/22418768/7da1de29-33b9-4d2a-ad5c-a9e788301f1a"> |
| Artifact page well | <img width="273" alt="image" src="https://github.com/PrefectHQ/prefect-design/assets/22418768/b044459e-7b75-4440-acf0-074e4b8045f6"> | <img width="268" alt="image" src="https://github.com/PrefectHQ/prefect-design/assets/22418768/88f98854-1286-4202-ba79-4bf3edddbeff"> |
=> Fix p-divider sometimes has 0 width.

demo/sections/components/Form.vue, src/components/Form/PForm.vue
`p-form` has built in spacing for child elements so that forms have consistent spacing. But its set to spacing 6 when we generally use spacing 4. So we have a decent bit of forms that have a `p-content` wrapping all of their content to get the right spacing. Updating `p-form` to use spacing 4 means we can just use the form by itself without a `p-content`.
=> Standardize gap spacing in p-form to match p-content

src/components/Card/PCard.vue
`p-card` uses `p-background` to determine the correctly background color. But it also has a `flat` prop which is supposed to remove the background. But if the `p-background` class is not removed the `flat` prop only works if its not nested within another element with `p-background`. 
Removing the `p-background` class when `flat` is used fixes this.
=> Fix p-card flat prop not working when nesting

src/components/DraggableList/PDraggableList.vue
These keep interfering with standard use. They aren't discoverable and are more than likely to be stumbled upon accidentally when attempting to do a different action. So removing for now until we can think this through better.
=> Remove keyboard shortcuts from draggable list

src/components/PopOver/PPopOver.vue
This adds a check for popover-content parents when attempting to auto-close a popover. This is for a very special use case of a pop-over inside a pop-over, where clicking the second one would dismiss before registering the link click:
=> Fix: check popover parent in auto-close

demo/sections/components/Checkbox.vue, src/components/Checkbox/PCheckbox.vue, src/styles/index.css
This PR enhances the `<p-checkbox />` component to better handle [indeterminate state checkboxes](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/checkbox#indeterminate_state_checkboxes). This PR adds a new section to the checkbox demo - check it out there. Below is a static version of it:
| Description | 📸 from Demo |
| ---- | ---- |
| None selected | ![image](https://github.com/PrefectHQ/prefect-design/assets/22418768/b36b3e0a-c33b-474b-acaf-a173f2c6793c) |
| Some selected | ![image](https://github.com/PrefectHQ/prefect-design/assets/22418768/39d3e823-3fc9-437f-a95d-abb9009a3c38) |
| All selected | ![image](https://github.com/PrefectHQ/prefect-design/assets/22418768/fab5c618-d678-45c6-b444-af13804bf1c6) |
At the moment like a lot of the other checkbox styles, the …
=> Indeterminate `<p-checkbox />` styles
